"""add reminder_days to jobs

Revision ID: df332810d759
Revises: 
Create Date: 2026-03-30 22:27:02.114012

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'df332810d759'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('reminder_days', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'reminder_days')
    # ### end Alembic commands ###
